apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: control-plane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: spice-platform
  destination:
    server: https://kubernetes.default.svc
    namespace: control-plane
  source:
    repoURL: __GITOPS_REPO_HTTPS_URL__
__GITOPS_APP_INSECURE__
    targetRevision: __GITOPS_TARGET_REVISION__
    path: deploy/helm/control-plane
    helm:
      releaseName: control-plane
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
