{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ include "control-plane.namespace" . }}
  labels:
    app.kubernetes.io/name: control-plane
{{- end }}
